In [2]:
import pandas as pd
import numpy as np

In [3]:
team_data = pd.read_csv("week2.csv")
team_data.dropna(inplace=True)


team_data

Year  Team Number  Rushing Yards  Passing Yards  Time Of Possession  \
0    2023            1          130.0          215.0               30.50   
1    2023            2          106.0          296.0               36.00   
2    2023            3          139.0          221.0               35.00   
3    2023            4          128.0          169.0               29.50   
4    2023            5          108.0          188.0               30.00   
..    ...          ...            ...            ...                 ...   
155  2023           28          159.0          206.0               26.75   
156  2023           29           82.0          311.0               33.50   
157  2023           30          120.0          317.0               36.00   
158  2023           31          141.0          200.0               36.75   
159  2023           32          122.0          266.0               33.75   

     Rushing Yards allowed  Passing Yards Allowed  Penalty Yards  Turnovers  \
0                    179.0                  203.0           36.0        2.0   
1                     72.0                  121.0           31.0        3.0   
2                    129.0                  104.0           88.0        1.0   
3                    132.0                  185.0           51.0        2.0   
4                    162.0                  262.0           11.0        0.0   
..                     ...                    ...            ...        ...   
155                   89.0                  297.0           57.0        0.0   
156                  102.0                  316.0           80.0        0.0   
157                   67.0                  169.0           54.0        0.0   
158                   61.0                  281.0           45.0        0.0   
159                  122.0                  277.0           71.0        0.0   

     Win  
0    0.0  
1    0.0  
2    1.0  
3    1.0  
4    0.0  
..   ...  
155  1.0  
156  1.0  
157  1.0  
158  1.0  
159  1.0  

[154 rows x 10 columns]

In [98]:
condition = team_data['Team Number'] == 1
filtered_teams = team_data.loc[condition]
arizona = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed','Penalty Yards', 'Turnovers']].median()
arizona_array = arizona.values
arizona_array

array([142. , 215. ,  30.5, 127. , 287. ,  55. ,   0. ])

In [99]:
condition = team_data['Team Number'] == 2
filtered_teams = team_data.loc[condition]
atlanta = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
atlanta_array = atlanta.values
atlanta_array

array([106. , 235. ,  35.5,  84. , 243. ,  50. ,   2. ])

In [100]:
condition = team_data['Team Number'] == 3
filtered_teams = team_data.loc[condition]
baltimore = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
baltimore_array = baltimore.values
baltimore_array

array([139.  , 221.  ,  32.25,  93.  , 188.  ,  56.  ,   1.  ])

In [101]:
condition = team_data['Team Number'] == 4
filtered_teams = team_data.loc[condition]
bills = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
bills_array = bills.values
bills_array

array([128., 267.,  30., 132., 185.,  45.,   1.])

In [102]:
condition = team_data['Team Number'] == 5
filtered_teams = team_data.loc[condition]
carolina = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
carolina_array = carolina.values
carolina_array

array([ 99. , 188. ,  29.5, 146. , 218. ,  45. ,   1. ])

In [103]:
condition = team_data['Team Number'] == 6
filtered_teams = team_data.loc[condition]
chicago = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
chicago_array = chicago.values
chicago_array

array([116., 169.,  30.,  97., 303.,  32.,   2.])

In [104]:
condition = team_data['Team Number'] == 7
filtered_teams = team_data.loc[condition]
cleveland = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards', 'Turnovers']].median()
cleveland_array = cleveland.values
cleveland_array

array([ 72., 216.,  33., 142., 221.,  40.,   1.])

In [105]:
condition = team_data['Team Number'] == 8
filtered_teams = team_data.loc[condition]
cincinatti = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
cincinnati_array = cincinatti.values
cincinnati_array

array([104.  , 146.  ,  29.25,  75.5 , 182.5 ,  44.  ,   3.  ])

In [106]:
condition = team_data['Team Number'] == 9
filtered_teams = team_data.loc[condition]
dallas = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
dallas_array = dallas.values
dallas_array

array([124. , 246. ,  34.5,  64. , 200. ,  60. ,   1. ])

In [107]:
condition = team_data['Team Number'] == 10
filtered_teams = team_data.loc[condition]
denver = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
denver_array = denver.values
denver_array

array([ 97.  , 277.  ,  26.25, 171.  , 266.  ,  39.  ,   2.  ])

In [108]:
condition = team_data['Team Number'] == 11
filtered_teams = team_data.loc[condition]
detroit = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
detroit_array = detroit.values
detroit_array

array([137.   , 230.5  ,  32.125,  63.   , 223.   ,  52.5  ,   1.   ])

In [109]:
condition = team_data['Team Number'] == 12
filtered_teams = team_data.loc[condition]
greenbay = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
greenbay_array = greenbay.values
greenbay_array

array([ 95. , 177. ,  27.5,  96. , 211. ,  31. ,   1. ])

In [110]:
condition = team_data['Team Number'] == 13
filtered_teams = team_data.loc[condition]
houston = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
houston_array = houston.values
houston_array

array([ 64., 310.,  31., 114., 227.,  46.,   0.])

In [111]:
condition = team_data['Team Number'] == 14
filtered_teams = team_data.loc[condition]
colts = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
colts_array = colts.values
colts_array

array([133., 196.,  29.,  89., 303.,  42.,   0.])

In [112]:
condition = team_data['Team Number'] == 15
filtered_teams = team_data.loc[condition]
kansascity = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards', 'Turnovers']].median()
kansascity_array = kansascity.values
kansascity_array

array([101., 293.,  32., 108., 228.,  84.,   2.])

In [113]:
condition = team_data['Team Number'] == 16
filtered_teams = team_data.loc[condition]
chargers = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
chargers_array = chargers.values
chargers_array

array([108.   , 215.5  ,  27.625, 113.   , 223.   ,  61.   ,   1.   ])

In [114]:
condition = team_data['Team Number'] == 17
filtered_teams = team_data.loc[condition]
rams = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
rams_array = rams.values
rams_array

array([ 89. , 221. ,  29.5, 159. , 206. ,  55. ,   1. ])

In [115]:
condition = team_data['Team Number'] == 18
filtered_teams = team_data.loc[condition]
jacksonville = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
jacksonville_array = jacksonville.values
jacksonville_array

array([105., 197.,  32.,  86., 298.,  25.,   1.])

In [116]:
condition = team_data['Team Number'] == 19
filtered_teams = team_data.loc[condition]
miami = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
miami_array = miami.values
miami_array

array([162., 262.,  30.,  88., 200.,  46.,   1.])

In [117]:
condition = team_data['Team Number'] == 20
filtered_teams = team_data.loc[condition]
minesota = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
minesota_array = minesota.values
minesota_array

array([ 70., 259.,  25.,  83., 171.,  45.,   2.])

In [118]:
condition = team_data['Team Number'] == 21
filtered_teams = team_data.loc[condition]
newengland = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
newengland_array = newengland.values
newengland_array

array([ 83., 200.,  28., 124., 244.,  45.,   2.])

In [119]:
condition = team_data['Team Number'] == 22
filtered_teams = team_data.loc[condition]
neworleans = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
neworleans_array = neworleans.values
neworleans_array


array([ 89. , 175. ,  31.5, 100. , 177. ,  83. ,   1. ])

In [120]:
condition = team_data['Team Number'] == 23
filtered_teams = team_data.loc[condition]
giants = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
giants_array = giants.values
giants_array

array([112. , 183. ,  31.5, 141. , 228. ,  45. ,   1. ])

In [121]:
condition = team_data['Team Number'] == 24
filtered_teams = team_data.loc[condition]
jets = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards', 'Turnovers']].median()
jets_array = jets.values
jets_array

array([108., 151.,  28., 139., 201.,  42.,   1.])

In [122]:
condition = team_data['Team Number'] == 25
filtered_teams = team_data.loc[condition]
raiders = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
raiders_array = raiders.values
raiders_array

array([ 76., 188.,  32., 110., 176.,  42.,   3.])

In [123]:
condition = team_data['Team Number'] == 26
filtered_teams = team_data.loc[condition]
philadelphia = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
philadelphia_array = philadelphia.values
philadelphia_array

array([159.  , 271.  ,  30.75,  54.  , 195.  ,  45.  ,   1.  ])

In [124]:
condition = team_data['Team Number'] == 27
filtered_teams = team_data.loc[condition]
pittsburgh = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards', 'Turnovers']].median()
pittsburgh_array = pittsburgh.values
pittsburgh_array

array([ 96.   , 201.   ,  28.625, 132.   , 251.5  ,  30.5  ,   1.   ])

In [125]:
condition = team_data['Team Number'] == 28
filtered_teams = team_data.loc[condition]
sanfrancisco = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
sanfrancisco_array = sanfrancisco.values
sanfrancisco_array

array([141.  , 251.  ,  29.25,  89.  , 174.  ,  57.  ,   0.  ])

In [126]:
condition = team_data['Team Number'] == 29
filtered_teams = team_data.loc[condition]
seattle = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
seattle_array = seattle.values
seattle_array

array([104. , 286.5,  32. ,  74. , 242. ,  72. ,   0.5])

In [127]:
condition = team_data['Team Number'] == 30
filtered_teams = team_data.loc[condition]
tampabay = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
tampabay_array = tampabay.values
tampabay_array

array([ 80.  , 222.  ,  27.25,  68.5 , 220.  ,  43.5 ,   1.  ])

In [128]:
condition = team_data['Team Number'] == 31
filtered_teams = team_data.loc[condition]
tennessee = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
tennessee_array = tennessee.values
tennessee_array

array([129., 200.,  29.,  78., 236.,  45.,   1.])

In [129]:
condition = team_data['Team Number'] == 32
filtered_teams = team_data.loc[condition]
washington = filtered_teams[['Rushing Yards', 'Passing Yards', 'Time Of Possession',
                        'Rushing Yards allowed', 'Passing Yards Allowed', 'Penalty Yards','Turnovers']].median()
washington_array = washington.values
washington_array

array([105., 258.,  30., 122., 277.,  40.,   0.])

In [130]:
team_data = team_data.drop("Team Number", axis = 1)


In [131]:
team_data= team_data.drop("Year", axis = 1)

team_data

Rushing Yards  Passing Yards  Time Of Possession  Rushing Yards allowed  \
0            130.0          215.0               30.50                  179.0   
1            106.0          296.0               36.00                   72.0   
2            139.0          221.0               35.00                  129.0   
3            128.0          169.0               29.50                  132.0   
4            108.0          188.0               30.00                  162.0   
..             ...            ...                 ...                    ...   
155          159.0          206.0               26.75                   89.0   
156           82.0          311.0               33.50                  102.0   
157          120.0          317.0               36.00                   67.0   
158          141.0          200.0               36.75                   61.0   
159          122.0          266.0               33.75                  122.0   

     Passing Yards Allowed  Penalty Yards  Turnovers  Win  
0                    203.0           36.0        2.0  0.0  
1                    121.0           31.0        3.0  0.0  
2                    104.0           88.0        1.0  1.0  
3                    185.0           51.0        2.0  1.0  
4                    262.0           11.0        0.0  0.0  
..                     ...            ...        ...  ...  
155                  297.0           57.0        0.0  1.0  
156                  316.0           80.0        0.0  1.0  
157                  169.0           54.0        0.0  1.0  
158                  281.0           45.0        0.0  1.0  
159                  277.0           71.0        0.0  1.0  

[154 rows x 8 columns]

In [132]:
X = team_data.drop("Win", axis = 1)
X

Rushing Yards  Passing Yards  Time Of Possession  Rushing Yards allowed  \
0            130.0          215.0               30.50                  179.0   
1            106.0          296.0               36.00                   72.0   
2            139.0          221.0               35.00                  129.0   
3            128.0          169.0               29.50                  132.0   
4            108.0          188.0               30.00                  162.0   
..             ...            ...                 ...                    ...   
155          159.0          206.0               26.75                   89.0   
156           82.0          311.0               33.50                  102.0   
157          120.0          317.0               36.00                   67.0   
158          141.0          200.0               36.75                   61.0   
159          122.0          266.0               33.75                  122.0   

     Passing Yards Allowed  Penalty Yards  Turnovers  
0                    203.0           36.0        2.0  
1                    121.0           31.0        3.0  
2                    104.0           88.0        1.0  
3                    185.0           51.0        2.0  
4                    262.0           11.0        0.0  
..                     ...            ...        ...  
155                  297.0           57.0        0.0  
156                  316.0           80.0        0.0  
157                  169.0           54.0        0.0  
158                  281.0           45.0        0.0  
159                  277.0           71.0        0.0  

[154 rows x 7 columns]

In [133]:
y = team_data["Win"]
y.head()

0    0.0
1    0.0
2    1.0
3    1.0
4    0.0
Name: Win, dtype: float64

In [134]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2
                                                   )

In [135]:
from sklearn.ensemble import RandomForestClassifier
np.random.seed(42)

model = RandomForestClassifier()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.8064516129032258

In [92]:
import ipywidgets as widgets
from IPython.display import display

team_one = widgets.Text(
    value = "", 
    description = "Team Name", 
    disabled = False
)
versus = widgets.Label(
    value = "VS"
)
team_two = widgets.Text(
    value = "", 
    description = "Team Name", 
    disabled = False
)
display(team_one, versus, team_two)

Text(value='', description='Team Name')

Label(value='VS')

Text(value='', description='Team Name')

In [160]:
team1 = team_one.value.lower()
team2 = team_two.value.lower()
team_arrays = {
    "arizona": arizona_array,
    "atlanta": atlanta_array,
    "baltimore": baltimore_array,
    "buffalo": bills_array,
    "carolina": carolina_array,
    "chicago": chicago_array,
    "cincinnati": cincinnati_array,
    "cleveland": cleveland_array,
    "dallas": dallas_array,
    "denver": denver_array,
    "detroit": detroit_array,
    "green_bay": greenbay_array,
    "houston": houston_array,
    "indianapolis": colts_array,
    "jacksonville": jacksonville_array,
    "kansas_city": kansascity_array,
    "las vegas": raiders_array,
    "los_angeles_chargers": chargers_array,
    "los_angeles_rams": rams_array,
    "miami": miami_array,
    "minnesota": minesota_array,
    "new england": newengland_array,
    "new orleans": neworleans_array,
    "new york giants": giants_array,
    "new york jets": jets_array,
    "philadelphia": philadelphia_array,
    "pittsburgh": pittsburgh_array,
    "san francisco": sanfrancisco_array,
    "seattle": seattle_array,
    "tampa bay": tampabay_array,
    "tennessee": tennessee_array,
    "washington": washington_array
}

def convert_team_name(team_name):
    if team_name in team_arrays: 
        return model.predict_proba(team_arrays[team_name].reshape(1,-1))
    else:
        print("That team is not in the NFL")

team_sum = {}
team_probabilities = {}
for team_name in team_arrays:
    team_probabilities[team_name] = convert_team_name(team_name)
    
if team1 in team_arrays:
    result1 = team_probabilities[team1]

if team2 in team_arrays:
    result2 = team_probabilities[team2]

winOdds = result1[0,1]
lossOdds = result1[0,0]

winOdds2 = result2[0,1]
lossOdds2 = result2[0,0]

oddsToWin1 = winOdds * lossOdds2
oddsToWin2 = winOdds2 * lossOdds

print(f"{team1.title()} has a {(result1[0,1])*100}% chance of winning the game.")
print(f"{team2.title()} has a {(result2[0,1])*100}% chance of winning the game.")
    


       
        

Green Bay has a 47.0% chance of winning the game.
Minnesota has a 21.0% chance of winning the game.


/Users/nickjenkins/Desktop/football_predictions/env/lib/python3.10/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/Users/nickjenkins/Desktop/football_predictions/env/lib/python3.10/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/Users/nickjenkins/Desktop/football_predictions/env/lib/python3.10/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/Users/nickjenkins/Desktop/football_predictions/env/lib/python3.10/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/Users/nickjenkins/Desktop/football_predictions/env/lib/python3.10/site-packages/sklearn/base.py